### ISSUE TITLE
Visual Editor: examples

### ISSUE THREAD

**Issue by samlown** [invopop/gobl.builder#59]
* When using the editor for the first time on an empty document, it can be frustrating to have to tap "+" for each individual field.

One possible solution would be to define "empty examples" for a specific set of schemas. When adding an `org.Party` for example, something like the following JSON would be used:

```json
{
  "name": "",
  "tax_id": {
     "country": "",
     "code": ""
  },
  "addresses": [
     {
       "num": "",
       "street": "",
       "locality": "",
       "region": ""
     }
  ],
  "emails": [
     {
        "addr": ""
     }
  ]
}
```

While not so useful for JSON, this would produce a lot of empty boxes in the Visual editor which can be easily removed later.

**Comment by juanmoli9** [comment]
Agreed

Juan Moliner Malaxechevarría

Co-Founder

invopop.com ( http://invopop.com/ )
