### ISSUE TITLE
Restrict to schema

### ISSUE THREAD

**Issue by samlown** [invopop/gobl.builder#6]
* As a developer incorporating GOBL Builder into my project, I'd like to be able to restrict the schema of the document to be *created* to the one I specify. For example, I'd like to ensure that my users only create documents with the schema `https://gobl.org/draft-0/bill/invoice` in my sales section.

Not sure what the best way to provide the schema would be. Perhaps as a query parameter?

It's tempting to expect the schema to be passed in a more compact form, like `bill.Invoice` or `bill/invoice`, but I think it's important to include the complete schema so it can be used with any other format in the future.

**Comment by dstotijn** [comment]
If we assume for now that `GOBLBuilder` will always work with one _single_ code editor model (Monaco supports multiple, e.g. rendered as tabs in VS Code — but we likely won't need that yet), we could expose a property to set the JSON schema for the document. For example, your project would use the component like this:

```svelte
<GOBLBuilder schema="https://gobl.org/draft-0/bill/invoice" />
```

It would then be up to the caller to decide where the `schema` prop value comes from. E.g. a piece of local state in the UI, perhaps based on something contextual from the "Console Labels" we're currently drafting. WDYT @samlown?

As for enforcing/validating against the supplied schema, I'll look into the Monaco Editor API. It should be possible to hook into the validation logic.

**Comment by dstotijn** [comment]
Added a [PR](https://github.com/invopop/gobl.builder/pull/10).

**Note:** For now in the "demo wrapper" (e.g. https://build.gobl.org), I've hardcoded the required schema to `https://gobl.org/draft-0/bill/invoice`. A follow up issue/PR will be to lift the "Load template..." logic out of the `GOBLBuilder` component; a parent/container project should do data loading and pass in data and/or required schema to `GOBLBuilder`. For the demo, we can keep the template loading logic, but it would be invoked from the demo wrapper code, *not* from within the `GOBLBuilder` component as we do right now.

**Comment by samlown** [comment]
Oh nice! That works quite well actually! Suggests sound good for the demo wrapper. That makes sense :+1:
